### ISSUE TITLE
Error accessing author info when processing webmentions

### ISSUE THREAD

**Issue by jonnybarnes** [jonnybarnes/jonnybarnes.uk#197]
Getting this error:

```
[2020-08-16 00:31:00] production.ERROR: Trying to access array offset on value of type bool {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type bool at /var/websites/jonnybarnes.uk/app/Jobs/SaveProfileImage.php:47)
[stacktrace]
#0 /var/websites/jonnybarnes.uk/app/Jobs/SaveProfileImage.php(47): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: App\\Jobs\\SaveProfileImage->handle()
#2 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#3 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#7 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#8 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#9 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#11 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow()
#12 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#13 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then()
#15 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#16 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#17 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()
#18 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(182): Illuminate\\Queue\\SyncQueue->push()
#19 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(158): Illuminate\\Bus\\Dispatcher->pushCommandToQueue()
#20 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\\Bus\\Dispatcher->dispatchToQueue()
#21 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(134): Illuminate\\Bus\\Dispatcher->dispatch()
#22 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(391): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#23 /var/websites/jonnybarnes.uk/app/Jobs/ProcessWebMention.php(73): dispatch()
#24 [internal function]: App\\Jobs\\ProcessWebMention->handle()
#25 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#26 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#27 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#28 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#29 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#30 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#31 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#32 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#34 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow()
#35 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#36 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then()
#38 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#39 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#40 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()
#41 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(182): Illuminate\\Queue\\SyncQueue->push()
#42 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(158): Illuminate\\Bus\\Dispatcher->pushCommandToQueue()
#43 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\\Bus\\Dispatcher->dispatchToQueue()
#44 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(134): Illuminate\\Bus\\Dispatcher->dispatch()
#45 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(391): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#46 /var/websites/jonnybarnes.uk/app/Http/Controllers/WebMentionsController.php(53): dispatch()
#47 [internal function]: App\\Http\\Controllers\\WebMentionsController->receive()
#48 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#49 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#50 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#51 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#52 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#53 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#54 /var/websites/jonnybarnes.uk/app/Http/Middleware/CSPHeader.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CSPHeader->handle()
#56 /var/websites/jonnybarnes.uk/app/Http/Middleware/ActivityStreamLinks.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ActivityStreamLinks->handle()
#58 /var/websites/jonnybarnes.uk/app/Http/Middleware/LocalhostSessionMiddleware.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\LocalhostSessionMiddleware->handle()
#60 /var/websites/jonnybarnes.uk/app/Http/Middleware/LinkHeadersMiddleware.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\LinkHeadersMiddleware->handle()
#62 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#64 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#66 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#68 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#70 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#71 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#73 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#75 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#77 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#78 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#79 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#80 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#81 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#82 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#84 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#85 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#86 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#87 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#88 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#89 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#90 /var/websites/jonnybarnes.uk/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#91 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#92 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#93 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#94 /var/websites/jonnybarnes.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#95 /var/websites/jonnybarnes.uk/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#96 {main}
"}
```

**Comment by jonnybarnes** [comment]
This is hopefully fixed in 631826923ab1b7796f250c2756c80789114467ac
